/sbin/wifi: Add load/unload support for wifi modules
Add load/unload support for wifi modules.

Change-Id: I854cfa67f5fe57cd0673c6041bd0fbd4eb67dca8
Signed-off-by: Pooventhiran G <quic_pooventh@quicinc.com>
(cherry picked from commit 7c2bd83edba0650793665fb27597d40c5bd09eac)

diff --git a/package/base-files/files/sbin/wifi b/package/base-files/files/sbin/wifi
--- a/package/base-files/files/sbin/wifi
+++ b/package/base-files/files/sbin/wifi
@@ -203,6 +203,29 @@ wifi_config() {
 	); done
 }
 
+wifi_unload() {
+       _wifi_updown "disable" "$1"
+       for driver in ${1:-$DRIVERS}; do (
+               if eval "type unload_$driver" 2>/dev/null >/dev/null; then
+                       eval "unload_$driver" || echo "$driver: unload failed" >&2
+               else
+                       echo "$driver: wifi unload not supported" >&2
+               fi
+       ); done
+}
+
+wifi_load() {
+       wifi_unload
+       for driver in ${1:-$DRIVERS}; do (
+               if eval "type load_$driver" 2>/dev/null >/dev/null; then
+                       eval "load_$driver" || echo "$driver: load failed" >&2
+               else
+                       echo "$driver: wifi load not supported" >&2
+               fi
+       ); done
+       _wifi_updown "enable" "$1"
+}
+
 start_net() {(
 	local iface="$1"
 	local config="$2"
@@ -282,6 +305,8 @@ case "$1" in
 	reload) wifi_reload "$2";;
 	reload_legacy) wifi_reload_legacy "$2";;
 	recover) wifi_recover "$2";;
+	load) wifi_load "$2";;
+	unload) wifi_unload "$2";;
 	--help|help) usage;;
 	reconf) wifi_updown "reconf" "$2";;
 	''|up) wifi_updown "enable" "$2";;
